#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Start aesdsocket at boot
### END INIT INFO

case "$1" in
  start)
    echo "Starting aesdsocket..."
    /usr/bin/aesdsocket &
    ;;
  stop)
    echo "Stopping aesdsocket..."
    killall aesdsocket
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0

