name: assignment6-yocto-test
on:
  push:
    branches:
      - '*'

jobs:
  full-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
          submodules: 'recursive'

      - name: Run build
        timeout-minutes: 600
        run: |
          docker run --rm \
            -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
            cuaesd/aesd-autotest:24-assignment6-yocto \
            --workdir=${GITHUB_WORKSPACE} \
            ./build.sh

      - name: Run full test
        timeout-minutes: 15
        run: |
          docker run --rm \
            -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
            cuaesd/aesd-autotest:24-assignment6-yocto \
            --workdir=${GITHUB_WORKSPACE} \
            ./full-test.sh

