name: assignment6-yocto-test

on:
  push:
    branches:
      - '*'  # Run on any branch push

jobs:
  full-test:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v3
        with:
          clean: false
          submodules: 'recursive'

      # Step 2: Run the build script
      - name: Run build
        timeout-minutes: 600
        run: ./build.sh

      # Step 3: Run the full test script
      - name: Run full test
        timeout-minutes: 15
        run: ./full-test.sh

